### ISSUE TITLE
Cannot open IDE due to HTTP 403 error

### ISSUE THREAD

**Issue by superera** [kendryte/kendryte-ide#102]
- IDE Version: SELF_VERSION=20190604.4
- Platform: Windows 

### Steps to Reproduce:
open IDE when this error message pops up
 HTTP 403: http://kendryte-ide.s3-website.cn-northwest-1.amazonaws.com.cn/3rd-party/versions.json
    at _loadJson(E:\K210\K210\shell\library\network.ts:49:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)

### More info:

Fail to start IDE

**Comment by clveryang** [comment]
I also meet this trouble ,why no  one to fix it ??

**Comment by superera** [comment]
> I also meet this trouble ,why no one to fix it ??

I ask the same question in Kendryte Community, they suggest VScode + toolchain instead...
dont know why they still didnt fix it..

**Comment by clveryang** [comment]
> > I also meet this trouble ,why no one to fix it ??
> 
> I ask the same question in Kendryte Community, they suggest VScode + toolchain instead... dont know why they still didnt fix it..
Thanks, I will try VScode + toolchain, things become complex...
