### ISSUE TITLE
Fail to Start Kendryte IDE on macOS Mojave 10.14.3 (18D109)

### ISSUE THREAD

**Issue by lymzzyh** [kendryte/kendryte-ide#23]
- IDE Version: 20190130.2(latest now)
- Platform:  Mac(macOS Mojave 10.14.3 (18D109))

### Steps to Reproduce:

1. Double click `KendryteIDE.command` to Start

### More info:

```bash
Last login: Sun Feb 17 16:21:26 on ttys003
/Users/zhangyihong/Documents/KendryteIDE/KendryteIDE.command ; exit;
➜  ~ /Users/zhangyihong/Documents/KendryteIDE/KendryteIDE.command ; exit;
__dirname=/Users/zhangyihong/Documents/KendryteIDE/Updater.app/Contents/Resources/app.asar/library
packageJson=/Users/zhangyihong/Documents/KendryteIDE/Updater.app/Contents/Resources/app.asar/package.json
SELF_VERSION=20190130.2
isBuilt=true
appRoot=/Users/zhangyihong/Documents/KendryteIDE
contentRoot=/Users/zhangyihong/Documents/KendryteIDE
configFile=/Users/zhangyihong/Documents/KendryteIDE/channel.json
creating progress window...
2019-02-17 16:21:49.439 Electron[4246:79962] *** WARNING: Textured window <AtomNSWindow: 0x7fbe89d08b80> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
!! browser-window-created
[console][0] hello world
[console][0] __dirname=/Users/zhangyihong/Documents/KendryteIDE/Updater.app/Contents/Resources/app.asar/library
[console][0] packageJson=/Users/zhangyihong/Documents/KendryteIDE/Updater.app/Contents/Resources/app.asar/package.json
[console][0] SELF_VERSION=20190130.2
[console][0] isBuilt=true
[console][0] appRoot=/Users/zhangyihong/Documents/KendryteIDE
[console][0] contentRoot=/Users/zhangyihong/Documents/KendryteIDE
[console][0] configFile=/Users/zhangyihong/Documents/KendryteIDE/channel.json
[console][0] loadApplicationData
[console][0] [object Object]
[console][0] debug: SELF_VERSION=20190130.2
[console][0] debug: isBuilt=true
[console][0] debug: appRoot=/Users/zhangyihong/Documents/KendryteIDE
[console][0] debug: configFile=/Users/zhangyihong/Documents/KendryteIDE/channel.json
[console][0] animate
[console][2] error: Error: Your system temporary directory is too long, will cause connection error.
(value is: /var/folders/6q/tzt6h7vn0vd6ky43mdk_ftt00000gn/T/KendryteIDE_Cache)
    at Object.prepareRun (/Users/zhangyihong/Documents/KendryteIDE/shell/library/prepareRun.ts:14:9)
    at startMainLogic (/Users/zhangyihong/Documents/KendryteIDE/shell/main/main.ts:38:8)
[console][0] Action: Fail to Start
[console][0]         something wrong
[console][2] Uncaught Error: Your system temporary directory is too long, will cause connection error.
(value is: /var/folders/6q/tzt6h7vn0vd6ky43mdk_ftt00000gn/T/KendryteIDE_Cache)


```

**Comment by GongT** [comment]
I will fix this in few days, before I can make a release, you can use this workaround:
* Open a terminal
* `export TMPDIR=/private/tmp`
* Drop `1. KendryteIDE.command` to terminal window and hit Enter

**Comment by lymzzyh** [comment]
Thanks ,It works.

**Comment by Janezzliu** [comment]
我按照你说的做了，结果遇到这样一个问题：[https://forum.kendryte.com/topic/103/mac%E7%8E%AF%E5%A2%83%E7%9A%84ide%E6%89%93%E4%B8%8D%E5%BC%80/5](url)就是下载中断那个问题。
