### ISSUE TITLE
fail to start 

### ISSUE THREAD

**Issue by qwert1213131** [kendryte/kendryte-ide#25]
### log如下：

```
SELF_VERSION=20190221.1
isBuilt=true
appRoot=D:\Program Files\KendryteIDE
configFile=D:\Program Files\KendryteIDE\channel.json
connecting
-------------------------
Get thirdParty:http://kendryte-ide.s3-website.cn-northwest-1.amazonaws.com.cn/3rd-party/versions.json
Error: EISDIR: illegal operation on a directory, read
Fail to Start
something wrong
```

**Comment by GongT** [comment]
这次更新的离线包有问题。。。你看看LocalPackage文件夹里是不是有个文件夹叫 bundled-version.json。。

如果有的话，把它随便改个名，然后把里面的内容剪切到外面来，应该就好了

**Comment by qwert1213131** [comment]
出现新的错误了

**Comment by qwert1213131** [comment]
```
SELF_VERSION=20190221.1
isBuilt=true
appRoot=D:\Program Files\KendryteIDE
configFile=D:\Program Files\KendryteIDE\channel.json
connecting
-------------------------
Get thirdParty:http://kendryte-ide.s3-website.cn-northwest-1.amazonaws.com.cn/3rd-party/versions.json
no action on: cmake
no action on: hello-world-project
no action on: cmake-list-files
no action on: isp
no action on: python2library
no action on: openocd
no action on: toolchain
checking
Get registry:http://kendryte-ide.s3-website.cn-northwest-1.amazonaws.com.cn/release/IDE.beta.json
latest version: 1.30.2-beta
latest patch: 20190225.1
latest updater: 20190221.1
found local version: app_1.30.2-beta_20190225.1
    version=1.30.2-beta
    patch=20190225.1
local versions: 
1.30.2-beta @ 20190225.1
 
version and patch both same, just start .
check complete. 3 work to be done.
-------------------------
...
work no name:
work no name has done in 0.01s
starting
...
work launch application:
found local version: app_1.30.2-beta_20190225.1
    version=1.30.2-beta
    patch=20190225.1
local versions: 
1.30.2-beta @ 20190225.1
 
D:\Program Files\KendryteIDE\Application\app_1.30.2-beta_20190225.1\KendryteIDE.exe 
wd: D:\Program Files\KendryteIDE\Updater
removing directory: D:\Program Files\KendryteIDE\UserData\latest\tmp...
never exists...
Error: application quit too early
    at ChildProcess.logExit (D:\Program Files\shell\electron-main\spawn.ts:193:11)
    at ChildProcess.emit (events.js:187:15)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
Fail to Start
something wrong
```

**Comment by GongT** [comment]
看看日志：D:\Program Files\KendryteIDE\UserData\updater\user-data\logs

**Comment by qwert1213131** [comment]
### 日志如下：
```
SELF_VERSION=20190221.1
isBuilt=true
appRoot=D:\Program Files\KendryteIDE
configFile=D:\Program Files\KendryteIDE\channel.json
connecting
-------------------------
Get thirdParty:http://kendryte-ide.s3-website.cn-northwest-1.amazonaws.com.cn/3rd-party/versions.json
Will download object from:
    http://kendryte-ide.s3-website.cn-northwest-1.amazonaws.com.cn/3rd-party/download1/cmake-windows.7z
 extract to:
    D:\Program Files\KendryteIDE\LocalPackage\cmake
Will download object from:
    http://kendryte-ide.s3-website.cn-northwest-1.amazonaws.com.cn/3rd-party/download1/hello-world-project.7z
 extract to:
    D:\Program Files\KendryteIDE\LocalPackage\hello-world-project
Will download object from:
    http://kendryte-ide.s3-website.cn-northwest-1.amazonaws.com.cn/3rd-party/download1/cmake-list-files.7z
 extract to:
    D:\Program Files\KendryteIDE\LocalPackage\cmake-list-files
Will download object from:
    http://kendryte-ide.s3-website.cn-northwest-1.amazonaws.com.cn/3rd-party/download1/isp.7z
 extract to:
    D:\Program Files\KendryteIDE\LocalPackage\isp
Will download object from:
    http://kendryte-ide.s3-website.cn-northwest-1.amazonaws.com.cn/3rd-party/download1/python2library.7z
 extract to:
    D:\Program Files\KendryteIDE\LocalPackage\python2library
Will download object from:
    http://kendryte-ide.s3-website.cn-northwest-1.amazonaws.com.cn/3rd-party/download1/openocd-windows.7z
 extract to:
    D:\Program Files\KendryteIDE\LocalPackage\openocd
Will download object from:
    http://kendryte-ide.s3-website.cn-northwest-1.amazonaws.com.cn/3rd-party/download1/toolchain-windows.7z
 extract to:
    D:\Program Files\KendryteIDE\LocalPackage\toolchain
checking
Get registry:http://kendryte-ide.s3-website.cn-northwest-1.amazonaws.com.cn/release/IDE.beta.json
latest version: 1.30.2-beta
latest patch: 20190225.1
latest updater: 20190221.1
framework version has updated, from no any version to 1.30.2-beta
Will download object from:
    http://kendryte-ide.s3-website.cn-northwest-1.amazonaws.com.cn/release/beta/v1.30.2/IDE.20190225.1.win32.7z
 extract to:
    D:\Program Files\KendryteIDE\Application\app_1.30.2-beta_20190225.1
check complete. 43 work to be done.
-------------------------
...
<div class="work-start">work no name:</div>
<div class="work-end">work no name has done in 0.01s</div>
Downloading
cmake: http://kendryte-ide.s3-website.cn-northwest-1.amazonaws.com.cn/3rd-party/download1/cmake-windows.7z
<div class="work-start">work download - cmake: :</div>
check remote changed: {"if-none-match":"\"5e75cdbbcd5f1ab3037af6331b9ebbdf-2\""}
  -> NOT changed. continue download (from 12543656).
success, no need download any data.
<div class="work-end">work download - cmake:  has done in 0.10s</div>
Installing
cmake: D:\Program Files\KendryteIDE\LocalPackage\cmake
<div class="work-start">work extract (install) - cmake: :</div>
unzip C:\Users\ADMINI~1\AppData\Local\Temp\KendryteIDE_Cache\cmake-windows.7z -> D:\Program Files\KendryteIDE\LocalPackage\cmake
D:\Program Files\KendryteIDE\Updater\resources\app.asar.unpacked\node_modules\7zip-bin\win\x64\7za.exe -bso1 -bse1 -bsp2 x -oD:\Program Files\KendryteIDE\LocalPackage\cmake -y C:\Users\ADMINI~1\AppData\Local\Temp\KendryteIDE_Cache\cmake-windows.7z
7-Zip (a) 18.05 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-04-30
Scanning the drive for archives:
1 file, 12543656 bytes (12 MiB)
Extracting archive: C:\Users\ADMINI~1\AppData\Local\Temp\KendryteIDE_Cache\cmake-windows.7z
--
Path = C:\Users\ADMINI~1\AppData\Local\Temp\KendryteIDE_Cache\cmake-windows.7z
Type = 7z
Physical Size = 12543656
Headers Size = 57766
Method = LZMA2:26 LZMA:20 BCJ2
Solid = +
Blocks = 2
Everything is Ok
Folders: 100
Files: 5544
Size:       72765577
Compressed: 12543656
child dirs: bin, cmake-windows, doc, man, share
<div class="work-end">work extract (install) - cmake:  has done in 19.29s</div>
<div class="work-start">work no name:</div>
<div class="work-end">work no name has done in 0.01s</div>
Downloading
hello-world-project: http://kendryte-ide.s3-website.cn-northwest-1.amazonaws.com.cn/3rd-party/download1/hello-world-project.7z
<div class="work-start">work download - hello-world-project: :</div>
check remote changed: {"if-none-match":"\"3bbae5768909848f752028c9b7aba5e3\""}
  -> NOT changed. continue download (from 687).
success, no need download any data.
<div class="work-end">work download - hello-world-project:  has done in 0.09s</div>
Installing
hello-world-project: D:\Program Files\KendryteIDE\LocalPackage\hello-world-project
<div class="work-start">work extract (install) - hello-world-project: :</div>
unzip C:\Users\ADMINI~1\AppData\Local\Temp\KendryteIDE_Cache\hello-world-project.7z -> D:\Program Files\KendryteIDE\LocalPackage\hello-world-project
D:\Program Files\KendryteIDE\Updater\resources\app.asar.unpacked\node_modules\7zip-bin\win\x64\7za.exe -bso1 -bse1 -bsp2 x -oD:\Program Files\KendryteIDE\LocalPackage\hello-world-project -y C:\Users\ADMINI~1\AppData\Local\Temp\KendryteIDE_Cache\hello-world-project.7z
7-Zip (a) 18.05 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-04-30
Scanning the drive for archives:
1 file, 687 bytes (1 KiB)
Extracting archive: C:\Users\ADMINI~1\AppData\Local\Temp\KendryteIDE_Cache\hello-world-project.7z
--
Path = C:\Users\ADMINI~1\AppData\Local\Temp\KendryteIDE_Cache\hello-world-project.7z
Type = 7z
Physical Size = 687
Headers Size = 289
Method = LZMA2:12
Solid = +
Blocks = 1
Everything is Ok
Folders: 2
Files: 4
Size:       614
Compressed: 687
child dirs: README.md, hello-world-project, kendryte-package.json, src
<div class="work-end">work extract (install) - hello-world-project:  has done in 5.18s</div>
<div class="work-start">work no name:</div>
<div class="work-end">work no name has done in 0.01s</div>
Downloading
cmake-list-files: http://kendryte-ide.s3-website.cn-northwest-1.amazonaws.com.cn/3rd-party/download1/cmake-list-files.7z
<div class="work-start">work download - cmake-list-files: :</div>
check remote changed: {"if-none-match":"\"55ac54981d4ba4fc1e284b1704c3f806\""}
  -> NOT changed. continue download (from 2708).
success, no need download any data.
<div class="work-end">work download - cmake-list-files:  has done in 0.09s</div>
Installing
cmake-list-files: D:\Program Files\KendryteIDE\LocalPackage\cmake-list-files
<div class="work-start">work extract (install) - cmake-list-files: :</div>
unzip C:\Users\ADMINI~1\AppData\Local\Temp\KendryteIDE_Cache\cmake-list-files.7z -> D:\Program Files\KendryteIDE\LocalPackage\cmake-list-files
D:\Program Files\KendryteIDE\Updater\resources\app.asar.unpacked\node_modules\7zip-bin\win\x64\7za.exe -bso1 -bse1 -bsp2 x -oD:\Program Files\KendryteIDE\LocalPackage\cmake-list-files -y C:\Users\ADMINI~1\AppData\Local\Temp\KendryteIDE_Cache\cmake-list-files.7z
7-Zip (a) 18.05 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-04-30
Scanning the drive for archives:
1 file, 2708 bytes (3 KiB)
Extracting archive: C:\Users\ADMINI~1\AppData\Local\Temp\KendryteIDE_Cache\cmake-list-files.7z
--
Path = C:\Users\ADMINI~1\AppData\Local\Temp\KendryteIDE_Cache\cmake-list-files.7z
Type = 7z
Physical Size = 2708
Headers Size = 378
Method = LZMA2:13
Solid = +
Blocks = 1
Everything is Ok
Folders: 1
Files: 10
Size:       7915
Compressed: 2708
child dirs: afterProject.cmake, cmake-list-files, coreFlags.cmake, dumpConfig.cmake, fix9985.cmake, flash.cmake, ideSettings.cmake, macros.cmake, reset.cmake, toolchain.cmake
<div class="work-end">work extract (install) - cmake-list-files:  has done in 5.15s</div>
<div class="work-start">work no name:</div>
<div class="work-end">work no name has done in 0.01s</div>
Downloading
isp: http://kendryte-ide.s3-website.cn-northwest-1.amazonaws.com.cn/3rd-party/download1/isp.7z
<div class="work-start">work download - isp: :</div>
check remote changed: {"if-none-match":"\"5d077ba31046f551d43e0288d446b63a\""}
  -> NOT changed. continue download (from 15378).
success, no need download any data.
<div class="work-end">work download - isp:  has done in 0.08s</div>
Installing
isp: D:\Program Files\KendryteIDE\LocalPackage\isp
<div class="work-start">work extract (install) - isp: :</div>
unzip C:\Users\ADMINI~1\AppData\Local\Temp\KendryteIDE_Cache\isp.7z -> D:\Program Files\KendryteIDE\LocalPackage\isp
D:\Program Files\KendryteIDE\Updater\resources\app.asar.unpacked\node_modules\7zip-bin\win\x64\7za.exe -bso1 -bse1 -bsp2 x -oD:\Program Files\KendryteIDE\LocalPackage\isp -y C:\Users\ADMINI~1\AppData\Local\Temp\KendryteIDE_Cache\isp.7z
7-Zip (a) 18.05 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-04-30
Scanning the drive for archives:
1 file, 15378 bytes (16 KiB)
Extracting archive: C:\Users\ADMINI~1\AppData\Local\Temp\KendryteIDE_Cache\isp.7z
--
Path = C:\Users\ADMINI~1\AppData\Local\Temp\KendryteIDE_Cache\isp.7z
Type = 7z
Physical Size = 15378
Headers Size = 182
Method = LZMA2:48k
Solid = -
Blocks = 1
Everything is Ok
Folders: 1
Files: 1
Size:       34240
Compressed: 15378
child dirs: bootloader.bin, isp
<div class="work-end">work extract (install) - isp:  has done in 5.14s</div>
<div class="work-start">work no name:</div>
<div class="work-end">work no name has done in 0.01s</div>
Downloading
python2library: http://kendryte-ide.s3-website.cn-northwest-1.amazonaws.com.cn/3rd-party/download1/python2library.7z
<div class="work-start">work download - python2library: :</div>
check remote changed: {"if-none-match":"\"fc8cf59df21c9d08fe1fafdf031e90f4\""}
  -> NOT changed. continue download (from 144332).
success, no need download any data.
<div class="work-end">work download - python2library:  has done in 0.08s</div>
Installing
python2library: D:\Program Files\KendryteIDE\LocalPackage\python2library
<div class="work-start">work extract (install) - python2library: :</div>
unzip C:\Users\ADMINI~1\AppData\Local\Temp\KendryteIDE_Cache\python2library.7z -> D:\Program Files\KendryteIDE\LocalPackage\python2library
D:\Program Files\KendryteIDE\Updater\resources\app.asar.unpacked\node_modules\7zip-bin\win\x64\7za.exe -bso1 -bse1 -bsp2 x -oD:\Program Files\KendryteIDE\LocalPackage\python2library -y C:\Users\ADMINI~1\AppData\Local\Temp\KendryteIDE_Cache\python2library.7z
7-Zip (a) 18.05 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-04-30
Scanning the drive for archives:
1 file, 144332 bytes (141 KiB)
Extracting archive: C:\Users\ADMINI~1\AppData\Local\Temp\KendryteIDE_Cache\python2library.7z
--
Path = C:\Users\ADMINI~1\AppData\Local\Temp\KendryteIDE_Cache\python2library.7z
Type = 7z
Physical Size = 144332
Headers Size = 2022
Method = LZMA2:21
Solid = +
Blocks = 1
Everything is Ok
Folders: 2
Files: 148
Size:       1799596
Compressed: 144332
child dirs: UserDict.py, __future__.py, _abcoll.py, _sysconfigdata.py, _weakrefset.py, abc.py, codecs.py, copy.py, copy_reg.py, encodings, functools.py, genericpath.py, linecache.py, locale.py, macpath.py, ntpath.py, os.py, posixpath.py, python2library, re.py, site.py, sre_compile.py, sre_constants.py, sre_parse.py, stat.py, sysconfig.py, traceback.py, types.py, warnings.py, weakref.py
<div class="work-end">work extract (install) - python2library:  has done in 5.41s</div>
<div class="work-start">work no name:</div>
<div class="work-end">work no name has done in 0.00s</div>
Downloading
openocd: http://kendryte-ide.s3-website.cn-northwest-1.amazonaws.com.cn/3rd-party/download1/openocd-windows.7z
<div class="work-start">work download - openocd: :</div>
check remote changed: {"if-none-match":"\"1c583fd0f4eeed8b1f1a6a35cd28a122-2\""}
  -> NOT changed. continue download (from 16564693).
success, no need download any data.
<div class="work-end">work download - openocd:  has done in 0.07s</div>
Installing
openocd: D:\Program Files\KendryteIDE\LocalPackage\openocd
<div class="work-start">work extract (install) - openocd: :</div>
unzip C:\Users\ADMINI~1\AppData\Local\Temp\KendryteIDE_Cache\openocd-windows.7z -> D:\Program Files\KendryteIDE\LocalPackage\openocd
D:\Program Files\KendryteIDE\Updater\resources\app.asar.unpacked\node_modules\7zip-bin\win\x64\7za.exe -bso1 -bse1 -bsp2 x -oD:\Program Files\KendryteIDE\LocalPackage\openocd -y C:\Users\ADMINI~1\AppData\Local\Temp\KendryteIDE_Cache\openocd-windows.7z
7-Zip (a) 18.05 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-04-30
Scanning the drive for archives:
1 file, 16564693 bytes (16 MiB)
Extracting archive: C:\Users\ADMINI~1\AppData\Local\Temp\KendryteIDE_Cache\openocd-windows.7z
--
Path = C:\Users\ADMINI~1\AppData\Local\Temp\KendryteIDE_Cache\openocd-windows.7z
Type = 7z
Physical Size = 16564693
Headers Size = 717
Method = LZMA2:24 BCJ
Solid = +
Blocks = 2
Everything is Ok
Folders: 2
Files: 24
Size:       44141376
Compressed: 16564693
child dirs: JLink.exe, JLinkARM.dll, libusb-1.0.dll, openocd, openocd.exe, x64, zadig-2.4.exe, zadig.ini
<div class="work-end">work extract (install) - openocd:  has done in 6.09s</div>
<div class="work-start">work no name:</div>
<div class="work-end">work no name has done in 0.01s</div>
Downloading
toolchain: http://kendryte-ide.s3-website.cn-northwest-1.amazonaws.com.cn/3rd-party/download1/toolchain-windows.7z
<div class="work-start">work download - toolchain: :</div>
check remote changed: {"if-none-match":"\"9307a8012f1a3e0b97eaddb75502c520-28\""}
  -> NOT changed. continue download (from 230122428).
success, no need download any data.
<div class="work-end">work download - toolchain:  has done in 0.10s</div>
Installing
toolchain: D:\Program Files\KendryteIDE\LocalPackage\toolchain
<div class="work-start">work extract (install) - toolchain: :</div>
unzip C:\Users\ADMINI~1\AppData\Local\Temp\KendryteIDE_Cache\toolchain-windows.7z -> D:\Program Files\KendryteIDE\LocalPackage\toolchain
D:\Program Files\KendryteIDE\Updater\resources\app.asar.unpacked\node_modules\7zip-bin\win\x64\7za.exe -bso1 -bse1 -bsp2 x -oD:\Program Files\KendryteIDE\LocalPackage\toolchain -y C:\Users\ADMINI~1\AppData\Local\Temp\KendryteIDE_Cache\toolchain-windows.7z
7-Zip (a) 18.05 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-04-30
Scanning the drive for archives:
1 file, 230122428 bytes (220 MiB)
Extracting archive: C:\Users\ADMINI~1\AppData\Local\Temp\KendryteIDE_Cache\toolchain-windows.7z
--
Path = C:\Users\ADMINI~1\AppData\Local\Temp\KendryteIDE_Cache\toolchain-windows.7z
Type = 7z
Physical Size = 230122428
Headers Size = 74507
Method = Delta LZMA2:25 BCJ
Solid = +
Blocks = 6
Everything is Ok
Folders: 367
Files: 8139
Size:       1584070982
Compressed: 230122428
child dirs: bin, include, kendryte-toolchain, lib, libexec, riscv64-unknown-elf, share
<div class="work-end">work extract (install) - toolchain:  has done in 38.46s</div>
<div class="work-start">work no name:</div>
<div class="work-end">work no name has done in 0.04s</div>
Installing
app_1.30.2-beta_20190225.1
Downloading
IDE: http://kendryte-ide.s3-website.cn-northwest-1.amazonaws.com.cn/release/beta/v1.30.2/IDE.20190225.1.win32.7z
<div class="work-start">work download - IDE: :</div>
check remote changed: {"if-none-match":"\"0e653d2d1f4caabc880e86097af27caa-5\""}
  -> NOT changed. continue download (from 49983549).
success, no need download any data.
<div class="work-end">work download - IDE:  has done in 0.09s</div>
Installing
IDE: D:\Program Files\KendryteIDE\Application\app_1.30.2-beta_20190225.1
<div class="work-start">work extract (install) - IDE: :</div>
unzip C:\Users\ADMINI~1\AppData\Local\Temp\KendryteIDE_Cache\IDE.20190225.1.win32.7z -> D:\Program Files\KendryteIDE\Application\app_1.30.2-beta_20190225.1
D:\Program Files\KendryteIDE\Updater\resources\app.asar.unpacked\node_modules\7zip-bin\win\x64\7za.exe -bso1 -bse1 -bsp2 x -oD:\Program Files\KendryteIDE\Application\app_1.30.2-beta_20190225.1 -y C:\Users\ADMINI~1\AppData\Local\Temp\KendryteIDE_Cache\IDE.20190225.1.win32.7z
7-Zip (a) 18.05 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-04-30
Scanning the drive for archives:
1 file, 49983549 bytes (48 MiB)
Extracting archive: C:\Users\ADMINI~1\AppData\Local\Temp\KendryteIDE_Cache\IDE.20190225.1.win32.7z
--
Path = C:\Users\ADMINI~1\AppData\Local\Temp\KendryteIDE_Cache\IDE.20190225.1.win32.7z
Type = 7z
Physical Size = 49983549
Headers Size = 19485
Method = LZMA2:26 LZMA:20 BCJ2
Solid = +
Blocks = 2
Everything is Ok
Folders: 558
Files: 1415
Size:       284499564
Compressed: 49983549
child dirs: KendryteIDE.VisualElementsManifest.xml, KendryteIDE.exe, api-ms-win-core-console-l1-1-0.dll, api-ms-win-core-datetime-l1-1-0.dll, api-ms-win-core-debug-l1-1-0.dll, api-ms-win-core-errorhandling-l1-1-0.dll, api-ms-win-core-file-l1-1-0.dll, api-ms-win-core-file-l1-2-0.dll, api-ms-win-core-file-l2-1-0.dll, api-ms-win-core-handle-l1-1-0.dll, api-ms-win-core-heap-l1-1-0.dll, api-ms-win-core-interlocked-l1-1-0.dll, api-ms-win-core-libraryloader-l1-1-0.dll, api-ms-win-core-localization-l1-2-0.dll, api-ms-win-core-memory-l1-1-0.dll, api-ms-win-core-namedpipe-l1-1-0.dll, api-ms-win-core-processenvironment-l1-1-0.dll, api-ms-win-core-processthreads-l1-1-0.dll, api-ms-win-core-processthreads-l1-1-1.dll, api-ms-win-core-profile-l1-1-0.dll, api-ms-win-core-rtlsupport-l1-1-0.dll, api-ms-win-core-string-l1-1-0.dll, api-ms-win-core-synch-l1-1-0.dll, api-ms-win-core-synch-l1-2-0.dll, api-ms-win-core-sysinfo-l1-1-0.dll, api-ms-win-core-timezone-l1-1-0.dll, api-ms-win-core-util-l1-1-0.dll, api-ms-win-crt-conio-l1-1-0.dll, api-ms-win-crt-convert-l1-1-0.dll, api-ms-win-crt-environment-l1-1-0.dll, api-ms-win-crt-filesystem-l1-1-0.dll, api-ms-win-crt-heap-l1-1-0.dll, api-ms-win-crt-locale-l1-1-0.dll, api-ms-win-crt-math-l1-1-0.dll, api-ms-win-crt-multibyte-l1-1-0.dll, api-ms-win-crt-private-l1-1-0.dll, api-ms-win-crt-process-l1-1-0.dll, api-ms-win-crt-runtime-l1-1-0.dll, api-ms-win-crt-stdio-l1-1-0.dll, api-ms-win-crt-string-l1-1-0.dll, api-ms-win-crt-time-l1-1-0.dll, api-ms-win-crt-utility-l1-1-0.dll, bin, blink_image_resources_200_percent.pak, content_resources_200_percent.pak, content_shell.pak, d3dcompiler_47.dll, ffmpeg.dll, icudtl.dat, libEGL.dll, libGLESv2.dll, locales, msvcp140.dll, natives_blob.bin, node.dll, pdf_viewer_resources.pak, resources, snapshot_blob.bin, ucrtbase.dll, ui_resources_200_percent.pak, vcruntime140.dll, views_resources_200_percent.pak
<div class="work-end">work extract (install) - IDE:  has done in 14.47s</div>
starting
...
<div class="work-start">work launch application:</div>
found local version: app_1.30.2-beta_20190225.1
    version=1.30.2-beta
    patch=20190225.1
local versions: <ul><li>1.30.2-beta @ 20190225.1</li></ul><div>&nbsp;</div>
D:\Program Files\KendryteIDE\Application\app_1.30.2-beta_20190225.1\KendryteIDE.exe 
wd: D:\Program Files\KendryteIDE\Updater
removing directory: D:\Program Files\KendryteIDE\UserData\latest\tmp...

never exists...

Error: application quit too early
    at ChildProcess.logExit (D:\Program Files\shell\electron-main\spawn.ts:193:11)
    at ChildProcess.emit (events.js:187:15)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
Fail to Start
something wrong
```

**Comment by GongT** [comment]
可以尝试：
1. 删除整个Application 文件夹，然后重新等他下载
2. 看看 `D:\Program Files\KendryteIDE\UserData\latest\user-data\logs` 里最新的一个文件夹里的log

**Comment by qwert1213131** [comment]
@GongT 
很奇怪，没有这个latest文件夹

**Comment by GongT** [comment]
那么打开一个cmd（不要管理员权限）    
然后运行 D:\Program Files\KendryteIDE\Application\xxxxxx\Kendryte IDE.exe 试试    
（直接打开这个目录把exe拖到cmd里按回车就可以）

顺便建议放到不带空格的目录里，能减少各种疑难问题（

**Comment by qwert1213131** [comment]
@GongT 
非常感谢，我把整个工程文件夹移到没有空格的目录下，正常了
